name: Update node version - nix flake
on:
  push:
    branches:
      - release-please--branches--master--components--clever-tools
jobs:
  check-if-update-required:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          with:
            fetch-depth: 2
      - name: generate git diff
        id: generated_git_diff
        run: |
          echo "DIFF_RESULT=$(git diff origin/master ./package.json)" >> $GITHUB_OUTPUT
      - name: check git diff
        run: |
          if [[ "${{ steps.generate_git_diff.outputs.DIFF_RESULT }}" =~ .*"volta".* ]]; then
            echo "It's there."
          fi
  check-node-version:
    runs-on: ubuntu-latest
    outputs:
      NODE_VERSION: ${{ steps.output_node_version.outputs.NODE_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - id: get_package_json_content
        run: |
          {
            echo 'PACKAGE_JSON_CONTENT<<EOF'
            cat ./package.json
            echo EOF
          } >> $GITHUB_OUTPUT
      - id: extract_node_version
        run: echo "NODE_VERSION=${{ fromJSON(steps.get_package_json_content.outputs.PACKAGE_JSON_CONTENT).volta.node }}" >> $GITHUB_OUTPUT
      - name: output node version
        id: output_node_version
        run: echo ${{ steps.extract_node_version.outputs.NODE_VERSION }}
