name: Update node version - nix flake
on:
  push:
    branches:
      - 'release-please--branches--master--components--clever-tools'
    paths:
      - 'package.json'
jobs:
  get-major-node-version:
    runs-on: ubuntu-latest
    outputs:
      nodeVersion: ${{ steps.extract_major_node_version.outputs.MAJOR_NODE_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - id: get_package_json_content
        run: |
          {
            echo 'PACKAGE_JSON_CONTENT<<EOF'
            cat ./package.json
            echo EOF
          } >> $GITHUB_OUTPUT
      - id: extract_node_version
        run: echo "NODE_VERSION=${{ fromJSON(steps.get_package_json_content.outputs.PACKAGE_JSON_CONTENT).volta.node }}" >> $GITHUB_OUTPUT
      - name: extract major node version
        id: extract_major_node_version
        run: |
          echo "MAJOR_NODE_VERSION=$(echo ${{ steps.extract_node_version.outputs.NODE_VERSION }} | sed 's/\..\+//g')" >> $GITHUB_OUTPUT
      - name: check
        run: echo ${{ steps.extract_major_node_version.outputs.MAJOR_NODE_VERSION }}
  update-nix-flake-node-version:
    runs-on: ubuntu-latest
    needs: get-major-node-version
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
      - name: replace nix flake node version
        run: sed -r -i "s/(nodejs-.._x)/nodejs-${{ needs.get-major-node-version.outputs.nodeVersion }}_x/gm" flake.nix
      - run: |
          git config --global user.name 'Florian Sanders'
          git config --global user.email 'florian.sanders@clever-cloud.com'
          git status
          git add flake.nix
          git commit -m "chore(flake): update node version"
          git push
