name: Update nix flake
on:
  push:
    branches:
      - master
      - 'hotfix/**'
jobs:
  Prefetch-npm-deps:
    runs-on: ubuntu-latest
    outputs:
      NPM_DEPS_HASH: ${{ steps.prefetch.outputs.NPM_DEPS_HASH }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.PERSO_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install prefetch-npm-deps
        run: nix-env -i prefetch-npm-deps -f '<nixpkgs>'
      - name: prefetch
        id: prefetch
        run: echo "NPM_DEPS_HASH=$(prefetch-npm-deps package-lock.json)" >> $GITHUB_OUTPUT
      - name: escape
        id: escape
        run: echo "NPM_DEPS_HASH_ESCAPED=$(echo ${{ steps.prefetch.outputs.NPM_DEPS_HASH }} | sed 's/\//\\\\\//gip')" >> $GITHUB_OUTPUT
      - name: update
        run: sed -i "s/sha[^\"]\+/${{ steps.escape.outputs.NPM_DEPS_HASH_ESCAPED }}/" flake.nix
      - run: git add .
      - run: nix flake update
      - run: |
          git config --global user.name 'Florian Sanders'
          git config --global user.email 'florian.sanders@clever-cloud.com'
          git status
          git commit -m "chore(flake): update nix flake"
          git push
